export default [
  'Spring Boot',
  'Spring Framework',
  'Spring Data JPA',
  'Hibernate',
  'Spock',
  'Drools',
  'REST',
  'SOLID',
  'OOP',
  'Data Structure',
  'Algorithms',
  'Microsoft SQL Server',
  'Maven',
  'Agile Development & Scrum',
];
